CREATE DATABASE CUSTOMER;
SELECT * FROM CUSTOMER;
CREATE TABLE CUSTOMER(
 C_ID INT PRIMARY KEY,NAME VARCHAR(40),CITY VARCHAR(20),GRADE INT,ID INT);
 
 INSERT INTO CUSTOMER VALUES(101,"PREETHI","DELHI",98,5001),(102,"VARUN","BENGALURE",94,5002),(103,"NIKHIL","ASSOM",99,5003),(104,"ARJUN","LOHORE",88,5004),(105,"PRAKRUTHI","NELLORE",38,5005),(106,"RISHI","KOLKATA",55,5006),(107,"CHAITANYA","DELHI",23,5007);
 
 -- 1)WRITE SQL QUERY TO FIND OUT DETAILS OF CUSTOMERS WHOSE GRADE HAVE OF 100
 SELECT * FROM CUSTOMER WHERE GRADE>100;
 
 -- 2)WRITE SQL QUERY TO FIND OUT DETAILS OF CUSTOMERS WHOSE GRADE HAVE OF GREATER THAN 100
 SELECT * FROM CUSTOMER WHERE GRADE>=45;
 
 -- 3)WRITE SQL QUERY TO FIND OUT DETAILS OF CUSTOMERS WHOSE GRADE HAVE OF GREATER THAN 100 IN ASCENDING ORDER
  SELECT * FROM CUSTOMER WHERE GRADE>=45 ORDER BY GRADE ASC;
  
-- 4)WRITE SQL QUERY TO FIND OUT DETAILS OF CUSTOMERS WHO ARE LIVING IN ASSOM AND GRADE LESS THAN OR EQUAL TO 50
SELECT * FROM CUSTOMER WHERE CITY="ASSOM" AND GRADE>=50;

-- 5)WRITE SQL QUERY TO FIND OUT DETAILS OF CUSTOMERS WHO ARE FROM  ASSOM OR HAVE A GRADDE ABOVE THAN
  SELECT * FROM CUSTOMER WHERE CITY="ASSOM" OR GRADE >90;
  SELECT * FROM CUSTOMER;
  
-- 6)WRITE SQL QUERY TO FIND OUT DETAILS OF CUSTOMERS WHO ARE EITHER FROM THE KERALA CITY OR WHO DONOT HAVE GRADE MORE THAN 100
  SELECT * FROM CUSTOMER WHERE CITY="KERELA" OR NOT GRADE >90;
  
-- 7)WHO DONOT BELONG TO CITY MUMBAI OR HAVE GRADE THAT EXCEEDS 88
SELECT * FROM CUSTOMER WHERE CITY !="MUMBAI" OR GRADE >88;-- IT WONT GIVE CORRECT DATA BECAUSE BOTH CONDITIONS SHOULD MATCH
SELECT * FROM CUSTOMER WHERE CITY !="MUMBAI" AND GRADE >88;-- HERE SATISFIES THE CONDITIONS.

-- FIND THE ORDER DETAILS EXCLUDING THE DATE 30-04-2023 AND ID MORETHAN 5002 OR PURCHASE AMOUNT >1000
CREATE TABLE ORDERS(
ORDERNO INT,
PURCHASE_AMOUNT INT,
ORDER_DATE DATE,
CID INT,
ID INT
);
  
INSERT INTO ORDERS VALUES(1,1200,'2023-04-23',101,5001),
(2,1250,'2023-04-26',102,5002),
(3,1500,'2023-04-28',103,5003),
(4,2000,'2023-04-20',104,5004),
(5,2300,'2023-04-30',105,5005),
(6,1200,'2023-04-30',106,5006),
(7,3900,'2023-04-27',107,5007);

SELECT * FROM ORDERS WHERE NOT ORDER_DATE="2023-04-30" AND ID>5002 OR PURCHASE_AMOUNT>1000;

CREATE TABLE  SALESMAN(
SALEMAN_ID INT PRIMARY KEY,NAME VARCHAR(20),CITY VARCHAR(20),COMMISION FLOAT);

INSERT INTO SALESMAN VALUES(200,"PREETHI","KURNOOL",0.45),(201,"PREET","KURNOOL",0.55),(202,"RIITU","KUR",0.23),(204,"PANDU","KANDYAL",0.55);

-- 1)TO FIND SALESMAN COMMISION WITHIN RANGE FROM 0.23 TO 0.43
SELECT * FROM SALESMAN WHERE COMMISION BETWEEN 0.23 AND 0.43;

-- 2)FIND OUT SALESMAN DETAILS WHOSE NAME STARTS WITH LETTER P
SELECT * FROM SALESMAN WHERE NAME LIKE "P%";
-- 3) CREATE A NEW COLUMN ADDRESS,INSERT SOME DATA IN THAT ADDRESS COLUMN AND DISPLAY ALL THOSE ADDRESS AS "SALESMAN ADDRESS" IN DESCENDING ORDER
ALTER TABLE SALESMAN ADD COLUMN ADDRESS VARCHAR(20);
SELECT * FROM SALESMAN;
UPDATE SALESMAN SET ADDRESS="H1" WHERE NAME="PREETHI";
UPDATE SALESMAN SET ADDRESS="H2" WHERE NAME="PREET";
UPDATE SALESMAN SET ADDRESS="H3" WHERE NAME="PANDU";
UPDATE SALESMAN SET ADDRESS="H1" WHERE NAME="RIITU";
SELECT address FROM SALESMAN ORDER BY ADDRESS ASC;
SELECT ADDRESS AS SALESMAN_ADDRESS FROM SALESMAN ORDER BY ADDRESS DESC;-- CHANGING NAME IN THE OUTPUT ITSELF INSTEAD OF USING 'ALTER'

