-- find all the rows where our session is python
SELECT * FROM RGM WHERE session = "PYTHON";
SELECT Name,college,address FROM RGM WHERE session="PYTHON";
SELECT * FROM RGM;
SELECT * FROM RGM WHERE session="SQL" AND address="DKMKKDMK";
SELECT * FROM RGM WHERE ADDRESS="DWARAKA";
SELECT * FROM RGM WHERE Name LIKE "N%";-- AFTER N WHATEVER NAME THERE IT WILL FETCH
SELECT * FROM RGM WHERE NAME LIKE "N%A";
SELECT * FROM RGM WHERE NAME LIKE "PR%";
SELECT * FROM RGM WHERE NAME LIKE "%A";
SELECT * FROM RGM WHERE NAME LIKE "%%R%";
SELECT * FROM RGM WHERE NAME LIKE "_I%";
SELECT * FROM RGM WHERE NAME LIKE "__K%";
SELECT * FROM RGM WHERE NAME LIKE "%T__";
SELECT * FROM RGM WHERE NAME NOT LIKE "P%";
SELECT * FROM RGM WHERE NAME NOT LIKE "N%";
SELECT * FROM RGM WHERE NAME NOT LIKE "%A";
SELECT * FROM RGM WHERE NAME NOT LIKE "_R%";
SELECT * FROM RGM WHERE NAME NOT LIKE "%L_";
SELECT * FROM RGM WHERE ADDRESS IN ('DEWRWR','DEWRTWR');
-- TO FETCH FROM MULTIPLE COLUMNS WE USE 'IN' 
-- TO FETCH FROM SINGLE COLUMN WE USE '='
SELECT * FROM RGM WHERE COLLEGE = 'IIT' OR COLLEGE="RGM";
SELECT * FROM RGM WHERE COLLEGE IN ('IIT','RGM');